#!/usr/bin/env python3
"""Docs that describe options the module does not have, and vice versa.

Documentation rots silently. Nothing fails when a Kconfig symbol is added and
never written down, or when one is renamed and the docs keep the old name --
the build is perfectly happy, and the person who finds out is a user copying a
line that does nothing. This is the cheapest guard against that: both
directions, every symbol, on every push.

Placeholders and deliberate references to things that do not exist go in
ALLOWED below, with the reason. That list is the point - it forces "this
symbol is not real" to be a decision someone wrote down rather than an
oversight nobody noticed.

Run: python scripts/check_docs.py
"""

import glob
import io
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')

# Named in the docs, not a config symbol of ours. Each needs a reason.
ALLOWED = {
    'NEXUS_LOG_LEVEL': 'generated by Zephyr from the log module template',
    'NEXUS_LOG_LEVEL_DBG': 'generated by Zephyr from the log module template',
    'NEXUS_PONG': 'the fictional game in the "adding a game" walkthrough',
    'NEXUS_SPLASH_TEXT': 'cited in splash.md as a switch that was removed',
    'NEXUS_X': 'prose placeholder in the CMake example',
}


def main():
    kc = io.open(os.path.join(ROOT, 'Kconfig'), encoding='utf-8').read()
    real = set(re.findall(r'^config (NEXUS_\w+)', kc, re.M))

    files = (sorted(glob.glob(os.path.join(ROOT, 'docs', '*.md')))
             + [os.path.join(ROOT, 'README.md')]
             + sorted(glob.glob(os.path.join(ROOT, 'examples', '**', '*.md'),
                                recursive=True)))
    docs = {os.path.relpath(f, ROOT).replace('\\', '/'):
            io.open(f, encoding='utf-8').read() for f in files}
    blob = '\n'.join(docs.values())

    # Docs write both CONFIG_NEXUS_FOO and, in tuning tables, bare NEXUS_FOO.
    named = set(re.findall(r'\b(?:CONFIG_)?(NEXUS_\w+)', blob))

    bad = 0

    print('Kconfig symbols: %d   docs scanned: %d' % (len(real), len(docs)))

    print('\nDocumented but not a real option')
    ghosts = sorted(s for s in named - real
                    if s not in ALLOWED and s.startswith('NEXUS_')
                    # A trailing underscore is prose for a wildcard -
                    # "NEXUS_SNAKE_* and NEXUS_BREAKOUT_* live in games.md" -
                    # and names a family, not a symbol.
                    and not s.endswith('_')
                    # dt-binding action IDs and C constants are not Kconfig
                    and not s.startswith(('NEXUS_ACT_', 'NEXUS_ACTION_',
                                          'NEXUS_GAME_SPEED_', 'NEXUS_TXT_',
                                          'NEXUS_PAD', 'NEXUS_GAP',
                                          'NEXUS_CONTENT_', 'NEXUS_C',
                                          'NEXUS_HUD_',
                                          'NEXUS_DONGLE', 'NEXUS_SOUND_')))
    for s in ghosts:
        where = ', '.join(f for f, t in docs.items() if s in t)
        print('  GHOST  %-36s %s' % (s, where))
        bad += 1
    if not ghosts:
        print('  none')

    print('\nReal options nobody wrote down')
    missing = sorted(real - named)
    for s in missing:
        print('  UNDOCUMENTED  %s' % s)
        bad += 1
    if not missing:
        print('  none')

    # An example a user copies must actually build. A splash path that is not
    # in the example is a FATAL_ERROR at configure time, by design.
    print('\nThe example config builds')
    for conf in glob.glob(os.path.join(ROOT, 'examples', '**', '*.conf'),
                          recursive=True):
        text = io.open(conf, encoding='utf-8').read()
        rel = os.path.relpath(conf, ROOT).replace('\\', '/')
        # Commented-out lines do not count: the example deliberately ships the
        # path commented, so a user can see the shape without the build dying.
        hits = re.findall(r'^CONFIG_NEXUS_SPLASH_IMAGE="([^"]+)"', text, re.M)
        if not hits:
            print('  ok    %s sets no splash image, so nothing to ship' % rel)
            continue
        for path in hits:
            img = os.path.join(os.path.dirname(conf), path)
            if os.path.exists(img):
                print('  ok    %s ships %s' % (rel, path))
            else:
                print('  FAIL  %s points at missing %s' % (rel, path))
                bad += 1

    print('\n%s' % ('FAILED (%d)' % bad if bad else 'PASSED'))
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
